### ISSUE TITLE
USER STORY: Change the venue and time reflecting to the poll result

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/love-running#3]
In order to **update the venue and time** as a **site administrator** I can **edit the particular content of the site**.

## Acceptance Criteria

- Acceptance Criteria 1: The administrator can edit the time and venue.
- Acceptance Criteria 2: An alert box pops up to confirm changes.
- Acceptance Criteria 3: Notify the user of any changes.

## Tasks

- [ ] Design an _edit_ icon and add it to the venue and time section.
- [ ] Create a JavaScript function to alert.
- [ ] Create the HTML and CSS for a banner that notifies changes.
