### ISSUE TITLE
USER STORY: Upload new images

### ISSUE THREAD

**Issue by sejungkwak** [sejungkwak/love-running#4]
In order to **share the latest event** as a **user** I can **upload the latest event pictures**.

## Acceptance Criteria

- Acceptance Criteria 1: The user can upload a photo.
- Acceptance Criteria 2: The user can delete their own photo.
- Acceptance Criteria 3: The user can add a caption.

## Tasks

- [ ] Design an _Add Photo_ and _Edit Photo_ button.
- [ ] Create the HTML and CSS to add a photo and caption.
- [ ] Create a JavaScript function to handle user interaction.
